[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"


["sys-apps/earlyoom"]
source = "github"
github = "rfjakob/earlyoom"
use_latest_release = true
prefix = 'v'

["dev-util/codeberg-cli"]
source = "gitea"
gitea = "Aviac/codeberg-cli"
host = "codeberg.org"
use_latest_release = true
prefix = 'v'

["net-analyzer/snitch"]
source = "github"
github = "karol-broda/snitch"
use_latest_release = true
prefix = 'v'

["mvdan/sh"]
source = "github"
github = "mvdan/sh"
use_latest_release = true
prefix = 'v'
